<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class DepartmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $departments = [
            ['name' => 'Adquisiciones'],
            ['name' => 'Alcoholes'],
            ['name' => 'Alumbrado Publico'],
            ['name' => 'Asistencia Social'],
            ['name' => 'Asuntos Internos'],
            ['name' => 'Atencion Ciudadana'],
            ['name' => 'Auditoria Financiera'],
            ['name' => 'Auditorio Expoferia'],
            ['name' => 'Auxiliar Administrativo'],
            ['name' => 'Bacheo'],
            ['name' => 'Bibliotecas'],
            ['name' => 'Bomberos'],
            ['name' => 'Capacitacion y Desarrollo'],
            ['name' => 'Centro de Tecnologias de la Informacion'],
            ['name' => 'Comunicacion Social'],
            ['name' => 'Contabilidad'],
            ['name' => 'Contraloria Municipal'],
            ['name' => 'Control Vehicular'],
            ['name' => 'Coord de Promocion y Reclutamiento'],
            ['name' => 'Coordinacion y Proyectos'],
            ['name' => 'COPLADEM'],
            ['name' => 'Cuarto Regidor'],
            ['name' => 'Decimo Regidor'],
            ['name' => 'Decimocuarto Regidor'],
            ['name' => 'Decimoprimer Regidor'],
            ['name' => 'Decimoquinto Regidor'],
            ['name' => 'Decimosegundo Regidor'],
            ['name' => 'Decimotercer Regidor'],
            ['name' => 'Departamento Tecnico'],
            ['name' => 'Desarrollo Comunitario'],
            ['name' => 'Desarrollo Economico'],
            ['name' => 'Desarrollo Rural'],
            ['name' => 'Desarrollo Social'],
            ['name' => 'Desarrollo Urbano'],
            ['name' => 'Direccion de E'],
            ['name' => 'Direccion de Deportes'],
            ['name' => 'Direccion de Educacion'],
            ['name' => 'Direccion de Proteccion Civil'],
            ['name' => 'Direccion Juridica'],
            ['name' => 'Diseño e Imagen'],
            ['name' => 'Contabilidad y Egresos'],
            ['name' => 'Ejecucion Fiscal'],
            ['name' => 'Enlace SRE'],
            ['name' => 'Eventos Especiales'],
            ['name' => 'Gobernacion'],
            ['name' => 'Grupos Vulnerables'],
            ['name' => 'Guarderias'],
            ['name' => 'H Cabildo'],
            ['name' => 'Ingresos'],
            ['name' => 'Instituto Municipal de Cultura'],
            ['name' => 'Instituto Municipal de la Juventud'],
            ['name' => 'Instituto Municipal de la Mujer'],
            ['name' => 'Instituto Municipal de la Vivienda'],
            ['name' => 'Instituto Municipal de Planeacion'],
            ['name' => 'Instituto Municipal del Deporte'],
            ['name' => 'Junta Municipal de Reclutamiento'],
            ['name' => 'Juzgado Administrativo Municipal'],
            ['name' => 'Licitaciones'],
            ['name' => 'Limpieza'],
            ['name' => 'Medio Ambiente'],
            ['name' => 'Modulo SDARE'],
            ['name' => 'Noveno Regidor'],
            ['name' => 'Obras Publicas'],
            ['name' => 'Octavo Regidor'],
            ['name' => 'Oficialia Mayor'],
            ['name' => 'Otras Coordinaciones de Juventud'],
            ['name' => 'Panteones'],
            ['name' => 'Parques y Jardines'],
            ['name' => 'Parquimetros'],
            ['name' => 'Participacion Social'],
            ['name' => 'Patrimonio'],
            ['name' => 'Pensionados'],
            ['name' => 'Pensionados Confianza'],
            ['name' => 'Plazas y Mercados'],
            ['name' => 'Presidencia'],
            ['name' => 'Presupuestos'],
            ['name' => 'Prevencion del Delito'],
            ['name' => 'Prevencion Social'],
            ['name' => 'Primer Regidor'],
            ['name' => 'Procuraduria de la Mujer'],
            ['name' => 'Programas Especiales'],
            ['name' => 'Proteccion Ciudadana'],
            ['name' => 'Quinto Regidor'],
            ['name' => 'Rastro Municipal'],
            ['name' => 'Recursos Humanos'],
            ['name' => 'Relaciones Publicas'],
            ['name' => 'Relleno Sanitario'],
            ['name' => 'Salud Municipal'],
            ['name' => 'Secretaria del Ayuntamiento'],
            ['name' => 'Secretaria Privada'],
            ['name' => 'Segundo Regidor'],
            ['name' => 'Seguridad Publica y Vialidad'],
            ['name' => 'Septimo Regidor'],
            ['name' => 'Servicios Generales'],
            ['name' => 'Servicios Publicos'],
            ['name' => 'Sexto Regidor'],
            ['name' => 'Sindicato Municipal'],
            ['name' => 'Sindicatura'],
            ['name' => 'Supervision de Ingenieria'],
            ['name' => 'Taller Municipal'],
            ['name' => 'Teatro Alberto M Alvarado y Centro'],
            ['name' => 'Tercer Regidor'],
            ['name' => 'Tesoreria Municipal'],
            ['name' => 'Transito y Vialidad'],
            ['name' => 'UniCAD'],
            ['name' => 'Unidad Catastral'],
            ['name' => 'Unidad Transparencia y Acceso a la Informacion'],
            ['name' => 'Vivero'],
            ['name' => 'Estancia Infantil'],
            ['name' => 'Procuraduria'],
            ['name' => 'Direccion de Salud Municipal'],
            ['name' => 'Secretaria Particular'],
            ['name' => 'PRODEM'],
            ['name' => 'Direccion de Prensa'],
            ['name' => 'Secretaria Tecnica'],
        ];

        $data = array_map(function ($department) {
            return [
                'uuid' => Str::uuid(),
                'organization_id' => 1,
                'code' => null,
                'name' => $department['name'],
                'seal_image' => null,
                'start_date' => now(),
                'end_date' => null,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }, $departments);

        DB::table('departments')->insert($data);
    }
}